### ISSUE TITLE
Few clarifications Required

### ISSUE THREAD

**Issue by sonumkar** [newrelic/nri-oracledb#158]
^^ Provide a general summary of the issue in the title above. ^^ 

Do we need give the connection string along wih ./bin/nri-oracledb ? Because the config.yml file is not pickedup as i see.
Also it is mentioned that listener.ora is required for monitoring but it is not available with 19c instantclient. So do we need to configure it on our own ?
And am getting TNS lost contact issue is that because of above mentioned point.

Thanks in advance.

**Comment by paologallinaharbur** [comment]
In the config, you have the following to configure that:
```
# The service name for the Oracle instance
    SERVICE_NAME: ORCL
    # The host on which Oracle is listening. If omitted, defaults to 127.0.0.1
    HOSTNAME: oracle_host
    # The port on which Oracle is listening. If omitted, defaults to 1521
    PORT: 12345
    # Alternatively, a full connection string can be used. This takes priority over host, port, and service_name.
    # CONNECTION_STRING:   (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oraclehost)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=orcl)))
```

The infrastructure agent parses that and runs the integration.  The[ docs](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/) should provide guidance and solve your doubts 😃  

If you are not able to solve it, can you open a support ticket? 
They will be able to follow you through the process?
