### ISSUE TITLE
Few Metrics are missing

### ISSUE THREAD

**Issue by sonumkar** [newrelic/nri-oracledb#159]
## Description
I have integrated this awesome tool with Oracle PDB and gave the required permissions to a user. Later i found that few metrics are not being collected. Is this because of some limitation of the tool? Also if there is any way to collect all the metrics mentioned in the doc for an OraclePDB kindly help me. Thank you. :)

**Comment by sigilioso** [comment]
Hello,

Thanks for reporting this. 

I'd suggest to review the [SYS_METRICS_SOURCE](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/#instance-settings) value in the integration configuration, to set it up properly (considering your requirements).

If that doesn't help, could you open a support ticket?

They will be able to guide you through the configuration process.
