### ISSUE TITLE
update project to use golangci-lint

### ISSUE THREAD

**Issue by veeravallib** [newrelic/nri-oracledb#49]
The gometalinter seems to be deprecated. Can this project be updated to use golangci?

##### OS
- All of them

**Comment by camdencheek** [comment]
Hi @veeravallib  -- Thanks for the request. It's on our radar, but I haven't had time to get all the integrations switched over yet. Looking to switch sometime soon

**Comment by carlossscastro** [comment]
Closing this issue as this has been implemented
