### ISSUE TITLE
Improve metric descriptions docs with types: default,extended

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-oracledb#62]
Currently the integration has two different types of metrics, default and extended ones.

We should add which type of metrics is each of them in the [description of the doc](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/oracle-database-monitoring-integration#metrics)

Just for reference i used the following commands to get the a list of each one:

```
cat metric_definitions.go|grep "defaultMetric: false" -B3 -A1 |grep "name:" >exteded_metrics
cat metric_definitions.go|grep "defaultMetric: true" -B3 -A1 |grep "name:" >default_metrics
```

**Comment by mangulonr** [comment]
Documentation updated
https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/oracle-database-monitoring-integration/
