### ISSUE TITLE
Provide a docker image for nri-oracledb

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-oracledb#68]
## Is your feature request related to a problem? Please describe.

Most of New Relic integrations are available as docker images in the https://github.com/newrelic/infrastructure-bundle. However, `nri-oracle` requires specific libraries to be installed at runtime.

Adding this libraries to the infrastructure-bundle might prove complex and add some noticeable space overhead.

Another alternative could be to use the ODPI-C Docker image provided by Oracle: https://oracle.github.io/odpi/doc/installation.html#docker-files

However this would have the added complexity of having to install the agent ourselves.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
