### ISSUE TITLE
Upgrade build environment

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-oracledb#73]
Right now, we build `nri-oracle` in debian buster:

https://github.com/newrelic/nri-oracledb/blob/713f26f4f8bb4b2e8e0e70c1d667015816997be6/build/Dockerfile#L1

For most integrations this is not a problem. However, since `nri-oracle` needs CGO, building it in this platform will tie it to the LIBC version present there, which might prevent the integration to run on some environments.

We should upgrade the build environment to a more recent version.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
