### ISSUE TITLE
Oracle19_c verify that is possible to fetch all metrics with a single user

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-oracledb#76]
It has been reported that is not currently possible to fetch all the available metrics from both CDB and PDB levels with a single user. Currently the only known workaround is to use two users and to run the integration twice.

We should:
 - verify that this limitation is caused by a configuration issue or a product limitation(this issue was not reported yet)
     - if it is is a product limitation
         -  update the documentation explaining the issue
         -  change the integration to use a single user.
     - if it is configuration issue we should update the documentation explaining how to properly setup user permissions

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
