### ISSUE TITLE
 CUSTOM_METRICS_QUERY is emitting metrics without event_type

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-oracledb#85]
When setting a CUSTOM_METRICS_QUERY, the metric is emitted with an empty event_type so it's not added to any sample:

{"PixQueue0":"0","displayName":"xxx","entityName":"ora-instance:xxx","event_type":"","reportingEndpoint":"xxx.com:1521"}

It's not the case with queries created on  CUSTOM_METRICS_CONFIG that by default are added to OracleCustomSample.

**Comment by kang-makes** [comment]
`v3.1.1` released :)
