### ISSUE TITLE
Evaluation - Improve Used Percentage on tablespaces when auto extend is activated

### ISSUE THREAD

**Issue by mangulonr** [newrelic/nri-oracledb#89]
This task is about to evaluate the effort needed to properly calculate the usage percentage on tablespaces when auto extend is enabled in the namespace.

**Benefit**
If the alert threshold is set to generate an alert when the usage is over 90%, and the tablespace is auto extending when the usage is around 95%, I will end up with a lot of unnecessary alerts that I don't need to act upon.

**Behavior expected**
-- Does the tablespace has auto-extend?
-- NO
Then calculate the used space based on the current usage against the current size of the datafiles.
-- YES
Then calculate the used space based on the current usage against the maximum value of autoextend configured for the tablespace.

**More information**
[Tablespace metrics in NR docs](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/#tablespace-metric)
[Zendesk ticket](https://newrelic.zendesk.com/agent/tickets/475385)
[Tablespace metrics - Oracle docs](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/DBA_TABLESPACE_USAGE_METRICS.html#GUID-FE479528-BB37-4B55-92CF-9EC19EDF4F46)

**Comment by gsanchezgavier** [comment]
As per the [Oracle docs ](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/DBA_TABLESPACE_USAGE_METRICS.html#GUID-FE479528-BB37-4B55-92CF-9EC19EDF4F46) the metric `TABLESPACE_SIZE` (`tablespace.spaceReservedInBytes` by the integration) is already considering the `autoextend` feature along with the underlying storage. This metric is part of the `extended metrics` of the integation which are activated if `EXTENDED_METRICS: true` env var exist.
